name: Validate Data Factory

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
# Relies on the following secrets being configured in GitHub
# - secrets.AZURE_SUBSCRIPTION_ID
# - secrets.RESOURCE_GROUP_NAME
# - secrets.DATA_FACTORY_NAME
env:
  subscriptionId: c6b181c1-c585-4048-8a67-ebc99188d823
  resourceGroupName: rg-adf-development
  dataFactoryName: rg-adf-development
  dataFactoryId: '/subscriptions/${{ env.subscriptionId }}/resourceGroups/${{ env.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ env.dataFactoryName }}'
  # dataFactoryId: '/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }}'

jobs:
  PRValidate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Validate Data Factory resources
        uses: azure/data-factory-validate-action@v1.1.5
        with:
          id: ${{ env.dataFactoryId }}
          path: ./AzureDataFactory/src
