name: Validate Data Factory

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# Relies on the following secrets being configured in GitHub
# - secrets.AZURE_SUBSCRIPTION_ID
# - secrets.RESOURCE_GROUP_NAME
# - secrets.FACTORY_NAME
env:
  dataFactoryId: '/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/${{ secrets.FACTORY_NAME }}'

jobs:
  PRValidate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Validate Data Factory resources
        uses: azure/data-factory-validate-action@v1.1.5
        with:
          id: ${{ env.dataFactoryId }}
          path: ./AzureDataFactory/src
